repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]

# Exclude specific directories
exclude: "models/tts-arabic-pytorch/tts-arabic-pytorch,models/ArTST/ArTST,models/ArTST/ArTST-huggingface,models/ArTST/fairseq"