repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    # Run the linter.
    - id: ruff
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
  - id: shellcheck
    files: \.(bash|sh)$

# Exclude specific directories
exclude: "models/tts-arabic-pytorch/tts-arabic-pytorch,models/ArTST/ArTST,models/ArTST/ArTST-huggingface,models/ArTST/fairseq"