name: Delete Docker Image on Branch Deletion

on:
  delete:
    branches:
      - '*' # Trigger on deletion of any branch

jobs:
  delete_image:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Extract branch name
      - name: Extract deleted branch name
        id: get_branch
        run: |
          echo "##[group]Extracting deleted branch name"
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          echo "Deleted branch name: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
          echo "##[endgroup]"

      # Step 2: Log in to GitHub Container Registry
      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      # Step 3: Delete Docker image from GHCR
      - name: Delete Docker image from GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
        run: |
          IMAGE_TAG=${{ env.branch_name }}
          echo "Deleting Docker image with tag: $IMAGE_TAG"

          # Extract image details using the GitHub API
          REPO=${{ github.repository }}
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/$REPO/versions \
            | jq -r --arg tag "$IMAGE_TAG" '.[] | select(.metadata.container.tags[] == $tag) | .id' \
            | while read -r IMAGE_ID; do
              echo "Deleting image with ID $IMAGE_ID"
              curl -X DELETE \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/$REPO/versions/$IMAGE_ID
            done
