---
name: Build Docker Image

permissions:
  contents: read

on:
  issue_comment:
    types:
      - created
  push:

jobs:
  build:
    runs-on: second

    # if: >
    #   github.event_name == 'issue_comment' &&
    #   contains(github.event.comment.body, '@bot build') &&
    #   (github.event.issue.pull_request != null)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          secrets: |
            CDN_API_KEY=${{ secrets.CDN_API_KEY }}
