---
name: Manual Docker Image Build

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build Docker image from'
        required: true
        default: 'main'

jobs:
  build-image:
    runs-on: third
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Docker Buildx
        # yamllint disable-line
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: .
          tags: ghcr.io/${{github.repository}}:${{github.event.inputs.branch}}
          cache-from: type=gha,key=docker-build-cache
          cache-to: type=gha,key=docker-build-cache,mode=max
          build-args: |
            CDN_API_KEY=${{ secrets.CDN_API_KEY }}
