---
name: Docker Image Build

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main

jobs:
  build-image:
    runs-on: big-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        # yamllint disable-line
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991
        with:
          context: .
          tags: ghcr.io/${{github.repository}}:${{github.ref_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=min
          secrets: |
            CDN_API_KEY=${{ secrets.CDN_API_KEY }}
