name: Manual Trigger with Branch Selection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build Docker image from'
        required: true
        default: 'main'

jobs:
  builddd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}  # Use the selected branch

      - name: Deploy
        run: echo "Deploying from branch ${{ github.event.inputs.branch }}"
